### ISSUE TITLE
I got problem db.rs 42

### ISSUE THREAD

**Issue by varisz-developer** [batleforc/rust-template#1]
I already set DB_HOST, DB_PORT,DB_DATABASE ,DB_USER DB_PASSWORD.env 

`'
Loaded .env file
called `Result::unwrap()` on an `Err` value: Backend(Error { kind: Io, cause: Some(Os { code: 10054, kind: ConnectionReset, message: "An existing connection was forcibly closed by the remote host." }) })', src\model\db.rs:42:35`

I just run "cargo run"

**Comment by batleforc** [comment]
Hello,
Actually, the template is still a WIP. some bug may occur.
Have you used the docker-compose ?

**Comment by varisz-developer** [comment]
I use free postrgresql from render.com .

**Comment by batleforc** [comment]
Can you access from your computer the database with a tool like heidisql ?

**Comment by varisz-developer** [comment]
yes I can access by pgAdmin . DATABASE_URL like this "cer5q3sgqg486p6ppq8g-a.singapore-postgres.render.com"

**Comment by batleforc** [comment]
So, I may need some info:
- your rust version
- your dotenv without sensitive data (replace it with <--redacted-->)

**Comment by varisz-developer** [comment]
My Rust Version "rustc 1.66.1 (90743e729 2023-01-10)"

**.env**
RUST_LOG="trace"
DB_HOST=" <--redacted-->"
DB_PORT="5432"
DB_DATABASE=" <--redacted-->"
DB_USER=" <--redacted-->"
DB_PASSWORD=" <--redacted-->"

**Comment by batleforc** [comment]
So, I just ruined my night. :/
In order for the API to work with render.com and other remote PostgreSQL servers with TLS feature, I had to setup OpenSSL.
Fixed with 8bd05a6687e94f42e7e3c0c13e05a1010ca23b77
